export DOCKER_HOST_IP=${DOCKER_HOST_IP:-localhost}

echo DOCKER_HOST_IP is $DOCKER_HOST_IP

export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost/eventuate
export SPRING_DATASOURCE_USERNAME=eventuate
export SPRING_DATASOURCE_PASSWORD=eventuate
export SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
export EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS=localhost:9092
export EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING=localhost:2181
export SPRING_ELASTICSEARCH_URIS=http://localhost:9200
export SERVER_PORT=8080
