version: '3'
services:
  todo-service:
    build:
      context: ./todo-service
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION?}
    ports:
      - "8081:8080"
    volumes:
      - ./build/libs:/app
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  todo-view-service:
    build:
      context: ./todo-view-service
      args:
        baseImageVersion: ${EVENTUATE_JAVA_BASE_IMAGE_VERSION?}
    ports:
      - "8082:8080"
    volumes:
      - ./build/libs:/app
    depends_on:
      - kafka
      - zookeeper
      - elasticsearch
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_ELASTICSEARCH_REST_URIS: "elasticsearch:9200"
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9300

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    environment:
        - http.host=0.0.0.0
        - network.publish_host=0.0.0.0
        - discovery.type=single-node
        - xpack.security.enabled=false
    ports:
        - "9200:9200"
        - "9300:9300"

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-kafka:5.2.4"
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: eventuateio/eventuate-postgres:$EVENTUATE_COMMON_VERSION
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate

  adminer:
      image: adminer:4.3.1-standalone
      ports:
          - 9080:8080

  cdc-service:
    image: eventuateio/eventuate-cdc-service:$EVENTUATE_CDC_VERSION
    ports:
      - "8099:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_READER_NAME: PostgresPollingReader
      SPRING_PROFILES_ACTIVE: EventuatePolling
      EVENTUATE_OUTBOX_ID: 1
