version: 2.1
orbs:
  eventuate-gradle-build-and-test: "eventuate_io/eventuate-gradle-build-and-test@0.2.9"
workflows:
  version: 2.1
  build-test-and-deploy:
    jobs:
      - eventuate-gradle-build-and-test/build-and-test:
          name: single-module-mysql
          resource_class: large
          script: ./single-module/build-and-test-all-mysql.sh
          gradle_cache_command: cd single-module && ./gradlew testClasses
          machine_image: ubuntu-2204:2024.01.1
          java_version_to_install: '17'
          checksum_files: single-module/gradle.properties single-module/gradle/wrapper/gradle-wrapper.properties
      - eventuate-gradle-build-and-test/build-and-test:
          name: single-module-postgres
          resource_class: large
          script: ./single-module/build-and-test-all-postgres.sh
          gradle_cache_command: cd single-module && ./gradlew testClasses
          machine_image: ubuntu-2204:2024.01.1
          java_version_to_install: '17'
          checksum_files: single-module/gradle.properties single-module/gradle/wrapper/gradle-wrapper.properties
      - eventuate-gradle-build-and-test/build-and-test:
          name: multi-module-mysql
          resource_class: large
          script: ./multi-module/build-and-test-all-mysql.sh
          gradle_cache_command: cd multi-module && ./gradlew testClasses
          machine_image: ubuntu-2204:2024.01.1
          java_version_to_install: '17'
          checksum_files: multi-module/gradle.properties multi-module/gradle/wrapper/gradle-wrapper.properties
      - eventuate-gradle-build-and-test/build-and-test:
          name: multi-module-postgres
          resource_class: large
          script: ./multi-module/build-and-test-all-postgres.sh
          gradle_cache_command: cd multi-module && ./gradlew testClasses
          machine_image: ubuntu-2204:2024.01.1
          java_version_to_install: '17'
          checksum_files: multi-module/gradle.properties multi-module/gradle/wrapper/gradle-wrapper.properties
